apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBXKxalMPAmaYWB3nZBs0iXOMHZMjaVxVc7QGPPKy1j92zSVdvxNX+DdqcMuY1BNt9fM4PoT131l6ilO0IQmiPHPSh9Icmsaf3a9d98GpjB48yBAx87yFybAddImi+0mMLehJg9gIUJykfBcha6Cf6mFHMk2zF5rgE3xAv0PSv/0vI/rkyOzHzNeqhlz1niAUphCX70E9B0POfP74flCrX9c9N0nDIxl7TjjBcZ8gKrEFUD2O0w+T/3ktyGPYIDrZm5dAqAlnEOH56gd1Me79EBKQxH7KjzaJaHIIHh1zWGaAlW/z0Ih1uGRgEu54c44E6YOynmU5SEyhg0eoEXLxDMPadVdBFnM12y3/XmfClUEImXAkuC02jQ5yRA8Gai7myw93xWIrtaa1CXgUlHu35ht9egH2wQsRZZLLPRrHvntFZMUYH62yQNtWWsTmUitzg9wdg/5mFIKpqphKqoGLBAk9rA3dFmHBdn+n3qzjCkZGINVDq+5Ul/JAAz98WrhQESOAwMvu94MFpAq6M0fobEsWipM4rU8V8cc4iZVnD5nKnm1mGbegIOMpewj4mKI5FD8NXoVnF5V2r2kSUEOFv1CEkR+mxqNigZC+NKNFX5kDtzp2/qdugMZy3BffGPb36aOmRltoclf0xr9I9OQ7mLm7a8COmxqhCY/JkcRNX0JC6aWiEz8HFMHs19Tz6peYOm/dhK7A7ViNxLB4eoooa5MVrdpgrCwTzw+H4Cbwh3QrKf/Vh/dqH5
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque