apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-certs-cloudflare
  namespace: openshift-config
  labels:
    app: cert-manager
spec:
  secretName: api-certs-cloudflare
  secretTemplate:
    labels:
      app: cert-manager
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  subject:
    organizations:
      - vDude Enterprises
  commonName: 'api.k8s.vdude.io'
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - 'api.k8s.vdude.io'
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
